# Generated by Django 4.2.20 on 2025-04-12 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClassName', models.CharField(max_length=100, verbose_name='班级名')),
            ],
            options={
                'verbose_name': 'class',
                'verbose_name_plural': 'classes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.URLField(blank=True, max_length=256)),
                ('name', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='姓名')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.URLField(blank=True, max_length=256)),
                ('name', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='姓名')),
                ('cls', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system.class')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='2025:04:04/12/25-12:02:05', max_length=50, verbose_name='name')),
                ('create_Time', models.DateTimeField(auto_now_add=True, verbose_name='create_time')),
                ('content', models.JSONField()),
                ('has_submit', models.BooleanField(default=False, verbose_name='是否发布')),
                ('cls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.class')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Questionnaire_owner', to='system.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.ManyToManyField(related_name='classes', to='system.teacher'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=100)),
                ('answers', models.JSONField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.questionnaire')),
            ],
        ),
    ]
