# Generated by Django 4.2.20 on 2025-04-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'managed': False, 'verbose_name': 'class', 'verbose_name_plural': 'classes'},
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='name',
            field=models.CharField(default='2025:04:04/03/25-09:35:02', max_length=50, verbose_name='name'),
        ),
    ]
