# Generated by Django 4.2.20 on 2025-04-12 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='name',
            field=models.CharField(default='2025:04:04/12/25-12:15:46', max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='cls',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='system.class'),
        ),
    ]
