# Generated by Django 3.2.8 on 2025-03-12 08:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('name', models.CharField(default=datetime.datetime(2025, 3, 12, 16, 49, 24, 832879), max_length=50, primary_key=True, serialize=False, verbose_name='name')),
                ('create_Time', models.DateTimeField(auto_now_add=True, verbose_name='create time')),
                ('text', models.TextField(verbose_name='text')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Questionnaire_owner', to='system.teacher')),
            ],
        ),
    ]
