# Generated by Django 3.2.8 on 2025-03-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_alter_questionnaire_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='create_Time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='create_time'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='name',
            field=models.CharField(default='<function uuid4 at 0x7fa6c28b4d30>', max_length=50, primary_key=True, serialize=False, verbose_name='name'),
        ),
    ]
