# Generated by Django 3.2.8 on 2025-03-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_auto_20250314_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='name',
            field=models.CharField(default='2025:03:03/14/25-14:43:20', max_length=50, primary_key=True, serialize=False, verbose_name='name'),
        ),
    ]
